# Generated by Django 5.2.6 on 2025-09-18 10:45
# Add CustomerVendorPriceList model for price list assignment

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_create_item_stock_view'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerVendorPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updatedAt', models.DateTimeField(auto_now=True, blank=True, help_text='Timestamp when record was last updated', null=True)),
                ('deletedAt', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('isDeleted', models.BooleanField(default=False, help_text='Indicates if record is soft deleted')),
                ('createdBy', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customerVendorID', models.ForeignKey(help_text='Associated customer or vendor', on_delete=django.db.models.deletion.CASCADE, to='core.customervendor')),
                ('deletedBy', models.ForeignKey(blank=True, help_text='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('priceListID', models.ForeignKey(help_text='Default price list for this customer/vendor', on_delete=django.db.models.deletion.CASCADE, to='core.pricelist')),
                ('updatedBy', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer/Vendor Price List',
                'verbose_name_plural': 'Customer/Vendor Price Lists',
                'db_table': 'customerVendorPriceList',
                'ordering': ['customerVendorID__customerVendorName'],
                'unique_together': {('customerVendorID', 'priceListID')},
            },
        ),
    ]
