# Generated by Django 5.2.6 on 2025-09-23 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_agent_email_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemaster',
            name='agentID',
            field=models.ForeignKey(blank=True, help_text='Agent who created this invoice', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.agent'),
        ),
    ]
