# Generated by Django 5.2.6 on 2024-12-26 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_agentuserid_to_agentid'),
    ]

    operations = [
        # Database schema changes were already applied manually
        # This is a placeholder migration to maintain migration history
    ]